import { MigrationInterface, QueryRunner } from "typeorm";

export class AddMappingOverrideToImportSessions1779636094894 implements MigrationInterface {
    name = 'AddMappingOverrideToImportSessions1779636094894'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "mfa_configs" DROP CONSTRAINT "fk_mfa_configs_user"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "fk_refresh_tokens_organization"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "fk_refresh_tokens_user"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP CONSTRAINT "fk_auth_events_organization"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP CONSTRAINT "fk_auth_events_user"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "fk_role_permissions_permission"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "fk_role_permissions_role"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "fk_memberships_organization"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "fk_memberships_role"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "fk_memberships_user"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "fk_invitations_invited_by"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "fk_invitations_organization"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "fk_invitations_role"`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" DROP CONSTRAINT "fk_workflow_instances_definition"`);
        await queryRunner.query(`ALTER TABLE "workflow_events" DROP CONSTRAINT "fk_workflow_events_instance"`);
        await queryRunner.query(`ALTER TABLE "import_sessions" DROP CONSTRAINT "fk_import_sessions_created_by"`);
        await queryRunner.query(`ALTER TABLE "import_sessions" DROP CONSTRAINT "fk_import_sessions_organization"`);
        await queryRunner.query(`ALTER TABLE "import_files" DROP CONSTRAINT "fk_import_files_session"`);
        await queryRunner.query(`ALTER TABLE "import_files" DROP CONSTRAINT "fk_import_files_uploaded_by"`);
        await queryRunner.query(`ALTER TABLE "import_staging_entries" DROP CONSTRAINT "fk_import_staging_entries_file"`);
        await queryRunner.query(`ALTER TABLE "import_staging_entries" DROP CONSTRAINT "fk_import_staging_entries_session"`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" DROP CONSTRAINT "fk_entry_transformations_cancelled_by"`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" DROP CONSTRAINT "fk_entry_transformations_created_by"`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" DROP CONSTRAINT "fk_entry_transformations_org"`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" DROP CONSTRAINT "fk_entry_transformations_source_entry"`);
        await queryRunner.query(`ALTER TABLE "rules" DROP CONSTRAINT "fk_rules_created_by"`);
        await queryRunner.query(`ALTER TABLE "rules" DROP CONSTRAINT "fk_rules_org"`);
        await queryRunner.query(`ALTER TABLE "rules" DROP CONSTRAINT "fk_rules_updated_by"`);
        await queryRunner.query(`ALTER TABLE "rule_executions" DROP CONSTRAINT "fk_rule_executions_executed_by"`);
        await queryRunner.query(`ALTER TABLE "rule_executions" DROP CONSTRAINT "fk_rule_executions_org"`);
        await queryRunner.query(`ALTER TABLE "rule_executions" DROP CONSTRAINT "fk_rule_executions_rule"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "fk_documents_deleted_by"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "fk_documents_organization"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "fk_documents_uploaded_by"`);
        await queryRunner.query(`ALTER TABLE "document_entries" DROP CONSTRAINT "fk_document_entries_created_by"`);
        await queryRunner.query(`ALTER TABLE "document_entries" DROP CONSTRAINT "fk_document_entries_document"`);
        await queryRunner.query(`ALTER TABLE "document_entries" DROP CONSTRAINT "fk_document_entries_organization"`);
        await queryRunner.query(`ALTER TABLE "organization_accounting_configs" DROP CONSTRAINT "fk_organization_accounting_configs_organization"`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" DROP CONSTRAINT "fk_organization_chart_accounts_organization"`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" DROP CONSTRAINT "fk_organization_chart_accounts_parent"`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" DROP CONSTRAINT "fk_organization_chart_accounts_reference"`);
        await queryRunner.query(`DROP INDEX "public"."ix_refresh_tokens_token_hash"`);
        await queryRunner.query(`DROP INDEX "public"."ix_auth_events_org_module_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."ix_auth_events_org_module_action_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."ix_auth_events_org_entity_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."ix_memberships_organization_id_status"`);
        await queryRunner.query(`DROP INDEX "public"."ix_invitations_token_hash"`);
        await queryRunner.query(`DROP INDEX "public"."ix_import_staging_entries_errors_gin"`);
        await queryRunner.query(`DROP INDEX "public"."ix_documents_tags_gin"`);
        await queryRunner.query(`DROP INDEX "public"."ix_auth_events_user_id_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."ix_auth_events_organization_id_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."ix_auth_events_event_type_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."ix_reference_chart_accounts_applicable_systems"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "ck_memberships_status"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "ck_invitations_status"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "ck_organizations_type"`);
        await queryRunner.query(`ALTER TABLE "import_sessions" DROP CONSTRAINT "chk_import_sessions_source_type"`);
        await queryRunner.query(`ALTER TABLE "import_sessions" DROP CONSTRAINT "chk_import_sessions_status"`);
        await queryRunner.query(`ALTER TABLE "import_sessions" DROP CONSTRAINT "chk_import_sessions_total_lines_positive"`);
        await queryRunner.query(`ALTER TABLE "import_sessions" DROP CONSTRAINT "chk_import_sessions_error_lines_positive"`);
        await queryRunner.query(`ALTER TABLE "import_files" DROP CONSTRAINT "chk_import_files_status"`);
        await queryRunner.query(`ALTER TABLE "import_files" DROP CONSTRAINT "chk_import_files_size_positive"`);
        await queryRunner.query(`ALTER TABLE "import_files" DROP CONSTRAINT "chk_import_files_checksum_hex"`);
        await queryRunner.query(`ALTER TABLE "import_staging_entries" DROP CONSTRAINT "chk_import_staging_entries_row_positive"`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" DROP CONSTRAINT "chk_entry_transformations_type"`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" DROP CONSTRAINT "chk_entry_transformations_status"`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" DROP CONSTRAINT "chk_entry_transformations_cancelled_consistency"`);
        await queryRunner.query(`ALTER TABLE "rules" DROP CONSTRAINT "chk_rules_priority_positive"`);
        await queryRunner.query(`ALTER TABLE "rules" DROP CONSTRAINT "chk_rules_name_not_empty"`);
        await queryRunner.query(`ALTER TABLE "rule_executions" DROP CONSTRAINT "chk_rule_executions_mode"`);
        await queryRunner.query(`ALTER TABLE "rule_executions" DROP CONSTRAINT "chk_rule_executions_counts_positive"`);
        await queryRunner.query(`ALTER TABLE "rule_executions" DROP CONSTRAINT "chk_rule_executions_applied_lte_matched"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "chk_documents_size_positive"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "chk_documents_checksum_hex"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "chk_documents_ocr_status"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "chk_documents_tags_is_array"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "chk_documents_deleted_pair"`);
        await queryRunner.query(`ALTER TABLE "reference_chart_accounts" DROP CONSTRAINT "chk_reference_chart_accounts_code"`);
        await queryRunner.query(`ALTER TABLE "reference_chart_accounts" DROP CONSTRAINT "chk_reference_chart_accounts_class"`);
        await queryRunner.query(`ALTER TABLE "reference_chart_accounts" DROP CONSTRAINT "chk_reference_chart_accounts_account_type"`);
        await queryRunner.query(`ALTER TABLE "reference_chart_accounts" DROP CONSTRAINT "chk_reference_chart_accounts_normal_balance"`);
        await queryRunner.query(`ALTER TABLE "reference_chart_accounts" DROP CONSTRAINT "chk_reference_chart_accounts_applicable_systems"`);
        await queryRunner.query(`ALTER TABLE "organization_accounting_configs" DROP CONSTRAINT "chk_organization_accounting_configs_system"`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" DROP CONSTRAINT "chk_organization_chart_accounts_code"`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" DROP CONSTRAINT "chk_organization_chart_accounts_class"`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" DROP CONSTRAINT "chk_organization_chart_accounts_account_type"`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" DROP CONSTRAINT "chk_organization_chart_accounts_normal_balance"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "uq_memberships_user_organization"`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" DROP CONSTRAINT "uq_workflow_instances_target"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP COLUMN "module"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP COLUMN "entity_type"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP COLUMN "before"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP COLUMN "after"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP COLUMN "request_id"`);
        await queryRunner.query(`ALTER TABLE "import_sessions" ADD "mapping_override" jsonb`);
        await queryRunner.query(`ALTER TABLE "rule_executions" ADD "matches_snapshot" jsonb NOT NULL DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD "module" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD "action" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD "entity_type" text`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD "entity_id" uuid`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD "before" jsonb`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD "after" jsonb`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD "request_id" text`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "uq_refresh_tokens_token_hash"`);
        await queryRunner.query(`ALTER TABLE "auth_events" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "uq_permissions_code"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "uq_roles_code"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "uq_users_email"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "uq_invitations_token_hash"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "uq_organizations_slug"`);
        await queryRunner.query(`COMMENT ON COLUMN "import_files"."detected_headers" IS NULL`);
        await queryRunner.query(`ALTER TABLE "import_staging_entries" ALTER COLUMN "raw_values" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "import_staging_entries" ALTER COLUMN "mapped_values" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "import_staging_entries" ALTER COLUMN "errors" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" ALTER COLUMN "before_values" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" ALTER COLUMN "after_values" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "rules" ALTER COLUMN "conditions" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "rules" ALTER COLUMN "actions" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "rule_executions" ALTER COLUMN "scope" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "rule_executions" ALTER COLUMN "transformation_ids" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "documents" ALTER COLUMN "tags" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "documents" ALTER COLUMN "uploaded_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "auth_events" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_mfa_configs_user_id" ON "mfa_configs" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_refresh_tokens_token_hash" ON "refresh_tokens" ("token_hash") `);
        await queryRunner.query(`CREATE INDEX "ix_auth_events_event_type_created_at" ON "auth_events" ("event_type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "ix_auth_events_organization_id_created_at" ON "auth_events" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "ix_auth_events_user_id_created_at" ON "auth_events" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_permissions_code" ON "permissions" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_roles_code" ON "roles" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_memberships_user_organization" ON "memberships" ("user_id", "organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_invitations_token_hash" ON "invitations" ("token_hash") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_organizations_slug" ON "organizations" ("slug") `);
        await queryRunner.query(`CREATE INDEX "ix_auth_events_org_module_action_created_at" ON "auth_events" ("organization_id", "module", "action", "created_at") `);
        await queryRunner.query(`CREATE INDEX "ix_auth_events_org_module_created_at" ON "auth_events" ("organization_id", "module", "created_at") `);
        await queryRunner.query(`ALTER TABLE "mfa_configs" ADD CONSTRAINT "FK_37d13a4d24e4b7d986449bd1122" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_78a23ff687c363e19d1e69b1dbd" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD CONSTRAINT "FK_d27703f0a3d79ba424741807cb4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD CONSTRAINT "FK_5fe9a4f1220063f215bbce0f4cf" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "FK_7c1e2fdfed4f6838e0c05ae5051" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "FK_e5380c394ec7912046d07b54290" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "FK_2fb8d236390c9977525fc4596ad" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_42d1dbb4d85dc3643fdc6560af0" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_e4950c4d6aa2236f5213538e01a" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_29b1cef6891d9b9d4e35f793b81" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" ADD CONSTRAINT "FK_b3251ba9d143233fb45fecd3731" FOREIGN KEY ("workflow_definition_id") REFERENCES "workflow_definitions"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" ADD CONSTRAINT "FK_52b5b92a5be15d008ab01973d62" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_events" ADD CONSTRAINT "FK_d371246ed09d27e9895687efdde" FOREIGN KEY ("workflow_instance_id") REFERENCES "workflow_instances"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_sessions" ADD CONSTRAINT "FK_3d34f0989a05cc9c18c826b0bc7" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_sessions" ADD CONSTRAINT "FK_d799b7ab75284183fd23b79229f" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_files" ADD CONSTRAINT "FK_92bdd814caaeb9c68b8fddc8c89" FOREIGN KEY ("session_id") REFERENCES "import_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_files" ADD CONSTRAINT "FK_4c38487f2f305790fa956d58abc" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_staging_entries" ADD CONSTRAINT "FK_4dd31bf02ecdd99668a95d6084c" FOREIGN KEY ("session_id") REFERENCES "import_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_staging_entries" ADD CONSTRAINT "FK_322adb3ded5d398aa7aa1c02f88" FOREIGN KEY ("file_id") REFERENCES "import_files"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" ADD CONSTRAINT "FK_0ee7bc49b00b86bb0df66072ea2" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" ADD CONSTRAINT "FK_811dcd3020e897c4f71ea2742f6" FOREIGN KEY ("source_entry_id") REFERENCES "import_staging_entries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" ADD CONSTRAINT "FK_a634b25eb1338de4faf3f234c0d" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" ADD CONSTRAINT "FK_969e325ad2cc93f0b0cb6d14b3d" FOREIGN KEY ("cancelled_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rules" ADD CONSTRAINT "FK_eb409f7245642c7d8590d15624d" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rules" ADD CONSTRAINT "FK_58aadf65853b15fe35aa945fe2e" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rules" ADD CONSTRAINT "FK_0444cd046a0afe10c177a0d5c8b" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rule_executions" ADD CONSTRAINT "FK_2917dc712e594b47681bd67967c" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rule_executions" ADD CONSTRAINT "FK_c85272460674f9ab74f2473002b" FOREIGN KEY ("rule_id") REFERENCES "rules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rule_executions" ADD CONSTRAINT "FK_a9424a27dd7ca8136fddd91dd97" FOREIGN KEY ("executed_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_69427761f37533ae7767601a64b" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_b9e28779ec77ff2223e2da41f6d" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_entries" ADD CONSTRAINT "FK_3fecad922fb195a0e0050846642" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_entries" ADD CONSTRAINT "FK_76b2929336bdde9610f30b7865d" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_entries" ADD CONSTRAINT "FK_2e6880511aede5d2d985aef7725" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_accounting_configs" ADD CONSTRAINT "FK_09e8132f9e46dd5abefcd665855" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" ADD CONSTRAINT "FK_ac79249a14d6b62d5f92119f8d6" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" ADD CONSTRAINT "FK_8ab0c28e664d44336487ba7340d" FOREIGN KEY ("parent_id") REFERENCES "organization_chart_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" ADD CONSTRAINT "FK_07e1100efe15e0ec79b5cdd8e9a" FOREIGN KEY ("reference_account_id") REFERENCES "reference_chart_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" DROP CONSTRAINT "FK_07e1100efe15e0ec79b5cdd8e9a"`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" DROP CONSTRAINT "FK_8ab0c28e664d44336487ba7340d"`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" DROP CONSTRAINT "FK_ac79249a14d6b62d5f92119f8d6"`);
        await queryRunner.query(`ALTER TABLE "organization_accounting_configs" DROP CONSTRAINT "FK_09e8132f9e46dd5abefcd665855"`);
        await queryRunner.query(`ALTER TABLE "document_entries" DROP CONSTRAINT "FK_2e6880511aede5d2d985aef7725"`);
        await queryRunner.query(`ALTER TABLE "document_entries" DROP CONSTRAINT "FK_76b2929336bdde9610f30b7865d"`);
        await queryRunner.query(`ALTER TABLE "document_entries" DROP CONSTRAINT "FK_3fecad922fb195a0e0050846642"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_b9e28779ec77ff2223e2da41f6d"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_69427761f37533ae7767601a64b"`);
        await queryRunner.query(`ALTER TABLE "rule_executions" DROP CONSTRAINT "FK_a9424a27dd7ca8136fddd91dd97"`);
        await queryRunner.query(`ALTER TABLE "rule_executions" DROP CONSTRAINT "FK_c85272460674f9ab74f2473002b"`);
        await queryRunner.query(`ALTER TABLE "rule_executions" DROP CONSTRAINT "FK_2917dc712e594b47681bd67967c"`);
        await queryRunner.query(`ALTER TABLE "rules" DROP CONSTRAINT "FK_0444cd046a0afe10c177a0d5c8b"`);
        await queryRunner.query(`ALTER TABLE "rules" DROP CONSTRAINT "FK_58aadf65853b15fe35aa945fe2e"`);
        await queryRunner.query(`ALTER TABLE "rules" DROP CONSTRAINT "FK_eb409f7245642c7d8590d15624d"`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" DROP CONSTRAINT "FK_969e325ad2cc93f0b0cb6d14b3d"`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" DROP CONSTRAINT "FK_a634b25eb1338de4faf3f234c0d"`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" DROP CONSTRAINT "FK_811dcd3020e897c4f71ea2742f6"`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" DROP CONSTRAINT "FK_0ee7bc49b00b86bb0df66072ea2"`);
        await queryRunner.query(`ALTER TABLE "import_staging_entries" DROP CONSTRAINT "FK_322adb3ded5d398aa7aa1c02f88"`);
        await queryRunner.query(`ALTER TABLE "import_staging_entries" DROP CONSTRAINT "FK_4dd31bf02ecdd99668a95d6084c"`);
        await queryRunner.query(`ALTER TABLE "import_files" DROP CONSTRAINT "FK_4c38487f2f305790fa956d58abc"`);
        await queryRunner.query(`ALTER TABLE "import_files" DROP CONSTRAINT "FK_92bdd814caaeb9c68b8fddc8c89"`);
        await queryRunner.query(`ALTER TABLE "import_sessions" DROP CONSTRAINT "FK_d799b7ab75284183fd23b79229f"`);
        await queryRunner.query(`ALTER TABLE "import_sessions" DROP CONSTRAINT "FK_3d34f0989a05cc9c18c826b0bc7"`);
        await queryRunner.query(`ALTER TABLE "workflow_events" DROP CONSTRAINT "FK_d371246ed09d27e9895687efdde"`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" DROP CONSTRAINT "FK_52b5b92a5be15d008ab01973d62"`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" DROP CONSTRAINT "FK_b3251ba9d143233fb45fecd3731"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_29b1cef6891d9b9d4e35f793b81"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_e4950c4d6aa2236f5213538e01a"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_42d1dbb4d85dc3643fdc6560af0"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "FK_2fb8d236390c9977525fc4596ad"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "FK_e5380c394ec7912046d07b54290"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "FK_7c1e2fdfed4f6838e0c05ae5051"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP CONSTRAINT "FK_5fe9a4f1220063f215bbce0f4cf"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP CONSTRAINT "FK_d27703f0a3d79ba424741807cb4"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_78a23ff687c363e19d1e69b1dbd"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "mfa_configs" DROP CONSTRAINT "FK_37d13a4d24e4b7d986449bd1122"`);
        await queryRunner.query(`DROP INDEX "public"."ix_auth_events_org_module_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."ix_auth_events_org_module_action_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."uq_organizations_slug"`);
        await queryRunner.query(`DROP INDEX "public"."uq_invitations_token_hash"`);
        await queryRunner.query(`DROP INDEX "public"."uq_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."uq_memberships_user_organization"`);
        await queryRunner.query(`DROP INDEX "public"."uq_roles_code"`);
        await queryRunner.query(`DROP INDEX "public"."uq_permissions_code"`);
        await queryRunner.query(`DROP INDEX "public"."ix_auth_events_user_id_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."ix_auth_events_organization_id_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."ix_auth_events_event_type_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."uq_refresh_tokens_token_hash"`);
        await queryRunner.query(`DROP INDEX "public"."uq_mfa_configs_user_id"`);
        await queryRunner.query(`ALTER TABLE "auth_events" ALTER COLUMN "metadata" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "documents" ALTER COLUMN "uploaded_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "documents" ALTER COLUMN "tags" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "rule_executions" ALTER COLUMN "transformation_ids" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "rule_executions" ALTER COLUMN "scope" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "rules" ALTER COLUMN "actions" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "rules" ALTER COLUMN "conditions" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" ALTER COLUMN "after_values" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" ALTER COLUMN "before_values" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "import_staging_entries" ALTER COLUMN "errors" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "import_staging_entries" ALTER COLUMN "mapped_values" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "import_staging_entries" ALTER COLUMN "raw_values" SET DEFAULT '{}'`);
        await queryRunner.query(`COMMENT ON COLUMN "import_files"."detected_headers" IS 'Canonical header list detected during parsing (ordered JSON array of strings). NULL until the file is successfully parsed.'`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "uq_organizations_slug" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "uq_invitations_token_hash" UNIQUE ("token_hash")`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "uq_users_email" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "uq_roles_code" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "uq_permissions_code" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "auth_events" ALTER COLUMN "metadata" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "uq_refresh_tokens_token_hash" UNIQUE ("token_hash")`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP COLUMN "request_id"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP COLUMN "after"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP COLUMN "before"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP COLUMN "entity_type"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP COLUMN "module"`);
        await queryRunner.query(`ALTER TABLE "rule_executions" DROP COLUMN "matches_snapshot"`);
        await queryRunner.query(`ALTER TABLE "import_sessions" DROP COLUMN "mapping_override"`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD "request_id" text`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD "after" jsonb`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD "before" jsonb`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD "entity_id" uuid`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD "entity_type" text`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD "action" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD "module" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" ADD CONSTRAINT "uq_workflow_instances_target" UNIQUE ("organization_id", "target_type", "target_id")`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "uq_memberships_user_organization" UNIQUE ("user_id", "organization_id")`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" ADD CONSTRAINT "chk_organization_chart_accounts_normal_balance" CHECK ((normal_balance = ANY (ARRAY['D'::bpchar, 'C'::bpchar])))`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" ADD CONSTRAINT "chk_organization_chart_accounts_account_type" CHECK ((account_type = ANY (ARRAY['TITLE'::text, 'POSTING'::text])))`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" ADD CONSTRAINT "chk_organization_chart_accounts_class" CHECK (((class >= 1) AND (class <= 9)))`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" ADD CONSTRAINT "chk_organization_chart_accounts_code" CHECK ((code ~ '^[0-9]{1,10}$'::text))`);
        await queryRunner.query(`ALTER TABLE "organization_accounting_configs" ADD CONSTRAINT "chk_organization_accounting_configs_system" CHECK ((system = ANY (ARRAY['NORMAL'::text, 'MINIMAL'::text, 'ALLEGE'::text])))`);
        await queryRunner.query(`ALTER TABLE "reference_chart_accounts" ADD CONSTRAINT "chk_reference_chart_accounts_applicable_systems" CHECK (((array_length(applicable_systems, 1) >= 1) AND (applicable_systems <@ ARRAY['NORMAL'::text, 'MINIMAL'::text, 'ALLEGE'::text])))`);
        await queryRunner.query(`ALTER TABLE "reference_chart_accounts" ADD CONSTRAINT "chk_reference_chart_accounts_normal_balance" CHECK ((normal_balance = ANY (ARRAY['D'::bpchar, 'C'::bpchar])))`);
        await queryRunner.query(`ALTER TABLE "reference_chart_accounts" ADD CONSTRAINT "chk_reference_chart_accounts_account_type" CHECK ((account_type = ANY (ARRAY['TITLE'::text, 'POSTING'::text])))`);
        await queryRunner.query(`ALTER TABLE "reference_chart_accounts" ADD CONSTRAINT "chk_reference_chart_accounts_class" CHECK (((class >= 1) AND (class <= 9)))`);
        await queryRunner.query(`ALTER TABLE "reference_chart_accounts" ADD CONSTRAINT "chk_reference_chart_accounts_code" CHECK ((code ~ '^[0-9]{1,10}$'::text))`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "chk_documents_deleted_pair" CHECK ((((deleted_at IS NULL) AND (deleted_by IS NULL)) OR ((deleted_at IS NOT NULL) AND (deleted_by IS NOT NULL))))`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "chk_documents_tags_is_array" CHECK ((jsonb_typeof(tags) = 'array'::text))`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "chk_documents_ocr_status" CHECK ((ocr_status = ANY (ARRAY['pending'::text, 'processing'::text, 'processed'::text, 'failed'::text, 'skipped'::text])))`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "chk_documents_checksum_hex" CHECK ((sha256_checksum ~ '^[0-9a-f]{64}$'::text))`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "chk_documents_size_positive" CHECK ((size_bytes > 0))`);
        await queryRunner.query(`ALTER TABLE "rule_executions" ADD CONSTRAINT "chk_rule_executions_applied_lte_matched" CHECK ((applied_count <= matched_count))`);
        await queryRunner.query(`ALTER TABLE "rule_executions" ADD CONSTRAINT "chk_rule_executions_counts_positive" CHECK (((matched_count >= 0) AND (applied_count >= 0)))`);
        await queryRunner.query(`ALTER TABLE "rule_executions" ADD CONSTRAINT "chk_rule_executions_mode" CHECK ((mode = ANY (ARRAY['simulation'::text, 'apply'::text])))`);
        await queryRunner.query(`ALTER TABLE "rules" ADD CONSTRAINT "chk_rules_name_not_empty" CHECK ((char_length(TRIM(BOTH FROM name)) > 0))`);
        await queryRunner.query(`ALTER TABLE "rules" ADD CONSTRAINT "chk_rules_priority_positive" CHECK ((priority >= 0))`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" ADD CONSTRAINT "chk_entry_transformations_cancelled_consistency" CHECK (((status = 'cancelled'::text) = ((cancelled_at IS NOT NULL) AND (cancelled_by_id IS NOT NULL))))`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" ADD CONSTRAINT "chk_entry_transformations_status" CHECK ((status = ANY (ARRAY['active'::text, 'cancelled'::text])))`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" ADD CONSTRAINT "chk_entry_transformations_type" CHECK ((type = ANY (ARRAY['reclassification'::text, 'adjustment'::text, 'correction'::text, 'ventilation'::text, 'grouping'::text])))`);
        await queryRunner.query(`ALTER TABLE "import_staging_entries" ADD CONSTRAINT "chk_import_staging_entries_row_positive" CHECK ((row_number > 0))`);
        await queryRunner.query(`ALTER TABLE "import_files" ADD CONSTRAINT "chk_import_files_checksum_hex" CHECK ((sha256_checksum ~ '^[0-9a-f]{64}$'::text))`);
        await queryRunner.query(`ALTER TABLE "import_files" ADD CONSTRAINT "chk_import_files_size_positive" CHECK ((size_bytes > 0))`);
        await queryRunner.query(`ALTER TABLE "import_files" ADD CONSTRAINT "chk_import_files_status" CHECK ((status = ANY (ARRAY['uploaded'::text, 'parsing'::text, 'parsed'::text, 'parse_failed'::text])))`);
        await queryRunner.query(`ALTER TABLE "import_sessions" ADD CONSTRAINT "chk_import_sessions_error_lines_positive" CHECK (((error_lines >= 0) AND (error_lines <= total_lines)))`);
        await queryRunner.query(`ALTER TABLE "import_sessions" ADD CONSTRAINT "chk_import_sessions_total_lines_positive" CHECK ((total_lines >= 0))`);
        await queryRunner.query(`ALTER TABLE "import_sessions" ADD CONSTRAINT "chk_import_sessions_status" CHECK ((status = ANY (ARRAY['draft'::text, 'parsing'::text, 'parsed'::text, 'validated'::text, 'ready_for_import'::text, 'completed'::text, 'failed'::text])))`);
        await queryRunner.query(`ALTER TABLE "import_sessions" ADD CONSTRAINT "chk_import_sessions_source_type" CHECK ((source_type = ANY (ARRAY['csv'::text, 'excel'::text, 'sage'::text, 'txt'::text])))`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "ck_organizations_type" CHECK ((type = ANY (ARRAY['firm'::text, 'company'::text])))`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "ck_invitations_status" CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'expired'::text, 'revoked'::text])))`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "ck_memberships_status" CHECK ((status = ANY (ARRAY['active'::text, 'suspended'::text])))`);
        await queryRunner.query(`CREATE INDEX "ix_reference_chart_accounts_applicable_systems" ON "reference_chart_accounts" ("applicable_systems") `);
        await queryRunner.query(`CREATE INDEX "ix_auth_events_event_type_created_at" ON "auth_events" ("created_at", "event_type") `);
        await queryRunner.query(`CREATE INDEX "ix_auth_events_organization_id_created_at" ON "auth_events" ("created_at", "organization_id") `);
        await queryRunner.query(`CREATE INDEX "ix_auth_events_user_id_created_at" ON "auth_events" ("created_at", "user_id") `);
        await queryRunner.query(`CREATE INDEX "ix_documents_tags_gin" ON "documents" ("tags") `);
        await queryRunner.query(`CREATE INDEX "ix_import_staging_entries_errors_gin" ON "import_staging_entries" ("errors") `);
        await queryRunner.query(`CREATE INDEX "ix_invitations_token_hash" ON "invitations" ("token_hash") `);
        await queryRunner.query(`CREATE INDEX "ix_memberships_organization_id_status" ON "memberships" ("organization_id", "status") `);
        await queryRunner.query(`CREATE INDEX "ix_auth_events_org_entity_created_at" ON "auth_events" ("created_at", "entity_id", "entity_type", "organization_id") WHERE ((entity_type IS NOT NULL) AND (entity_id IS NOT NULL))`);
        await queryRunner.query(`CREATE INDEX "ix_auth_events_org_module_action_created_at" ON "auth_events" ("action", "created_at", "module", "organization_id") `);
        await queryRunner.query(`CREATE INDEX "ix_auth_events_org_module_created_at" ON "auth_events" ("created_at", "module", "organization_id") `);
        await queryRunner.query(`CREATE INDEX "ix_refresh_tokens_token_hash" ON "refresh_tokens" ("token_hash") `);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" ADD CONSTRAINT "fk_organization_chart_accounts_reference" FOREIGN KEY ("reference_account_id") REFERENCES "reference_chart_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" ADD CONSTRAINT "fk_organization_chart_accounts_parent" FOREIGN KEY ("parent_id") REFERENCES "organization_chart_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_chart_accounts" ADD CONSTRAINT "fk_organization_chart_accounts_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_accounting_configs" ADD CONSTRAINT "fk_organization_accounting_configs_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_entries" ADD CONSTRAINT "fk_document_entries_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_entries" ADD CONSTRAINT "fk_document_entries_document" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_entries" ADD CONSTRAINT "fk_document_entries_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "fk_documents_uploaded_by" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "fk_documents_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "fk_documents_deleted_by" FOREIGN KEY ("deleted_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rule_executions" ADD CONSTRAINT "fk_rule_executions_rule" FOREIGN KEY ("rule_id") REFERENCES "rules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rule_executions" ADD CONSTRAINT "fk_rule_executions_org" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rule_executions" ADD CONSTRAINT "fk_rule_executions_executed_by" FOREIGN KEY ("executed_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rules" ADD CONSTRAINT "fk_rules_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rules" ADD CONSTRAINT "fk_rules_org" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rules" ADD CONSTRAINT "fk_rules_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" ADD CONSTRAINT "fk_entry_transformations_source_entry" FOREIGN KEY ("source_entry_id") REFERENCES "import_staging_entries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" ADD CONSTRAINT "fk_entry_transformations_org" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" ADD CONSTRAINT "fk_entry_transformations_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "entry_transformations" ADD CONSTRAINT "fk_entry_transformations_cancelled_by" FOREIGN KEY ("cancelled_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_staging_entries" ADD CONSTRAINT "fk_import_staging_entries_session" FOREIGN KEY ("session_id") REFERENCES "import_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_staging_entries" ADD CONSTRAINT "fk_import_staging_entries_file" FOREIGN KEY ("file_id") REFERENCES "import_files"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_files" ADD CONSTRAINT "fk_import_files_uploaded_by" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_files" ADD CONSTRAINT "fk_import_files_session" FOREIGN KEY ("session_id") REFERENCES "import_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_sessions" ADD CONSTRAINT "fk_import_sessions_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_sessions" ADD CONSTRAINT "fk_import_sessions_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_events" ADD CONSTRAINT "fk_workflow_events_instance" FOREIGN KEY ("workflow_instance_id") REFERENCES "workflow_instances"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" ADD CONSTRAINT "fk_workflow_instances_definition" FOREIGN KEY ("workflow_definition_id") REFERENCES "workflow_definitions"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "fk_invitations_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "fk_invitations_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "fk_invitations_invited_by" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "fk_memberships_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "fk_memberships_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "fk_memberships_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_permission" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD CONSTRAINT "fk_auth_events_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD CONSTRAINT "fk_auth_events_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "fk_refresh_tokens_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "fk_refresh_tokens_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mfa_configs" ADD CONSTRAINT "fk_mfa_configs_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
