/**
 * Stable catalogue of business error codes.
 *
 * Codes are kept as a `const` object (not a TypeScript `enum`) so:
 *  - the wire format is always the string literal (no implicit numeric values),
 *  - the union type `ErrorCode` is derived directly from the catalogue
 *    (single source of truth shared with the HTTP status map),
 *  - frontend clients can pattern-match safely on the same strings without
 *    importing any backend code.
 *
 * Conventions:
 *  - Prefix groups by domain: `AUTH_*`, `ORG_*`, `FORBIDDEN_*`,
 *    `INVITATION_*`, `RBAC_*`.
 *  - Never reuse or rename a code: it is part of the public API contract.
 *  - Every code MUST have a matching entry in `http-status.map.ts`
 *    (compile-time enforced via `Record<ErrorCode, number>`).
 */

export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  AUTH_WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  AUTH_MFA_INVALID_CODE: 'AUTH_MFA_INVALID_CODE',
  AUTH_MFA_NOT_ENROLLED: 'AUTH_MFA_NOT_ENROLLED',
  AUTH_MFA_ALREADY_ENABLED: 'AUTH_MFA_ALREADY_ENABLED',
  AUTH_REFRESH_REUSE: 'AUTH_REFRESH_REUSE',

  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  ORG_LAST_ADMIN: 'ORG_LAST_ADMIN',
  ORG_NOTHING_TO_UPDATE: 'ORG_NOTHING_TO_UPDATE',

  FORBIDDEN_ROLE: 'FORBIDDEN_ROLE',
  FORBIDDEN_PERMISSION: 'FORBIDDEN_PERMISSION',
  FORBIDDEN_NO_MEMBERSHIP: 'FORBIDDEN_NO_MEMBERSHIP',

  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_ALREADY_USED: 'INVITATION_ALREADY_USED',
  INVITATION_ALREADY_PENDING: 'INVITATION_ALREADY_PENDING',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_REVOKED: 'INVITATION_REVOKED',

  RBAC_NO_POLICY_DECLARED: 'RBAC_NO_POLICY_DECLARED',
  RBAC_SYSTEM_ROLE_LOCKED: 'RBAC_SYSTEM_ROLE_LOCKED',

  // Module 2 — Plan comptable OHADA.
  CHART_ACCOUNT_NOT_FOUND: 'CHART_ACCOUNT_NOT_FOUND',
  CHART_ACCOUNT_CODE_TAKEN: 'CHART_ACCOUNT_CODE_TAKEN',
  CHART_ACCOUNT_INVALID_PARENT: 'CHART_ACCOUNT_INVALID_PARENT',
  CHART_ACCOUNT_INVALID_CODE: 'CHART_ACCOUNT_INVALID_CODE',
  CHART_ACCOUNT_NOT_DELETABLE: 'CHART_ACCOUNT_NOT_DELETABLE',
  CHART_ACCOUNT_IMMUTABLE_CODE: 'CHART_ACCOUNT_IMMUTABLE_CODE',
  ACCOUNTING_SYSTEM_REQUIRED: 'ACCOUNTING_SYSTEM_REQUIRED',

  // Module 3 — Import engine.
  IMPORT_SESSION_NOT_FOUND: 'IMPORT_SESSION_NOT_FOUND',
  IMPORT_SESSION_NOT_DRAFT: 'IMPORT_SESSION_NOT_DRAFT',
  IMPORT_SESSION_NOT_PARSED: 'IMPORT_SESSION_NOT_PARSED',
  IMPORT_FILE_NOT_FOUND: 'IMPORT_FILE_NOT_FOUND',
  IMPORT_FILE_TOO_LARGE: 'IMPORT_FILE_TOO_LARGE',
  IMPORT_FILE_DUPLICATE: 'IMPORT_FILE_DUPLICATE',
  IMPORT_UNSUPPORTED_FORMAT: 'IMPORT_UNSUPPORTED_FORMAT',
  IMPORT_FILE_PARSE_FAILED: 'IMPORT_FILE_PARSE_FAILED',
  IMPORT_SESSION_NOT_VALID: 'IMPORT_SESSION_NOT_VALID',
  IMPORT_COMMIT_UNBALANCED_GROUP: 'IMPORT_COMMIT_UNBALANCED_GROUP',
  IMPORT_COMMIT_FAILED: 'IMPORT_COMMIT_FAILED',
  IMPORT_SESSION_CANNOT_DELETE: 'IMPORT_SESSION_CANNOT_DELETE',

  // Module 8 wave 2 — Partner account lettering.
  LETTERING_NOT_FOUND: 'LETTERING_NOT_FOUND',
  LETTERING_LINES_REQUIRED: 'LETTERING_LINES_REQUIRED',
  LETTERING_UNBALANCED: 'LETTERING_UNBALANCED',
  LETTERING_MIXED_ACCOUNTS: 'LETTERING_MIXED_ACCOUNTS',
  LETTERING_LINE_ALREADY_USED: 'LETTERING_LINE_ALREADY_USED',
  LETTERING_NOT_PARTNER_ACCOUNT: 'LETTERING_NOT_PARTNER_ACCOUNT',
  LETTERING_LINE_NOT_VALIDATED: 'LETTERING_LINE_NOT_VALIDATED',
  LETTERING_ALREADY_BROKEN: 'LETTERING_ALREADY_BROKEN',

  // Module 9 — Financial reports.
  REPORT_INVALID_DATE_RANGE: 'REPORT_INVALID_DATE_RANGE',

  // Module 4 — Transformation Engine (wave 1).
  TRANSFORMATION_SOURCE_ENTRY_NOT_FOUND: 'TRANSFORMATION_SOURCE_ENTRY_NOT_FOUND',
  TRANSFORMATION_NO_FIELD_CHANGED: 'TRANSFORMATION_NO_FIELD_CHANGED',
  TRANSFORMATION_ADJUSTMENT_INVALID: 'TRANSFORMATION_ADJUSTMENT_INVALID',

  // Module 10 — Document engine (vague 1).
  DOC_NOT_FOUND: 'DOC_NOT_FOUND',
  DOC_FILE_REQUIRED: 'DOC_FILE_REQUIRED',
  DOC_FILE_TOO_LARGE: 'DOC_FILE_TOO_LARGE',
  DOC_MIME_REJECTED: 'DOC_MIME_REJECTED',
  DOC_STORAGE_FAILURE: 'DOC_STORAGE_FAILURE',

  // Module 5 — Rule Engine (wave 1).
  RULE_NOT_FOUND: 'RULE_NOT_FOUND',
  RULE_INVALID_CONDITION: 'RULE_INVALID_CONDITION',
  RULE_INVALID_ACTION: 'RULE_INVALID_ACTION',

  // Module 6 — Workflow engine (vague 1).
  WORKFLOW_INSTANCE_NOT_FOUND: 'WORKFLOW_INSTANCE_NOT_FOUND',
  WORKFLOW_TRANSITION_INVALID: 'WORKFLOW_TRANSITION_INVALID',
  WORKFLOW_LOCKED: 'WORKFLOW_LOCKED',

  // Module 8 — Journals & Entries (vague 1).
  JOURNAL_NOT_FOUND: 'JOURNAL_NOT_FOUND',
  JOURNAL_CODE_TAKEN: 'JOURNAL_CODE_TAKEN',
  JOURNAL_ENTRY_NOT_FOUND: 'JOURNAL_ENTRY_NOT_FOUND',
  JOURNAL_ENTRY_UNBALANCED: 'JOURNAL_ENTRY_UNBALANCED',
  JOURNAL_ENTRY_EMPTY_LINES: 'JOURNAL_ENTRY_EMPTY_LINES',
  JOURNAL_ENTRY_NON_POSTING_ACCOUNT: 'JOURNAL_ENTRY_NON_POSTING_ACCOUNT',
  JOURNAL_ENTRY_INVALID_LINE: 'JOURNAL_ENTRY_INVALID_LINE',
  JOURNAL_ENTRY_IMMUTABLE: 'JOURNAL_ENTRY_IMMUTABLE',
  JOURNAL_ENTRY_ALREADY_CANCELLED: 'JOURNAL_ENTRY_ALREADY_CANCELLED',
  ACCOUNTING_PERIOD_NOT_FOUND: 'ACCOUNTING_PERIOD_NOT_FOUND',
  ACCOUNTING_PERIOD_CLOSED: 'ACCOUNTING_PERIOD_CLOSED',
  ACCOUNTING_PERIOD_HAS_DRAFTS: 'ACCOUNTING_PERIOD_HAS_DRAFTS',
  ACCOUNTING_PERIOD_REOPEN_REASON_REQUIRED: 'ACCOUNTING_PERIOD_REOPEN_REASON_REQUIRED',
  ACCOUNTING_PERIOD_OVERLAPS: 'ACCOUNTING_PERIOD_OVERLAPS',

  // Module 13 — TVA & Déclarations fiscales.
  TVA_CODE_NOT_FOUND: 'TVA_CODE_NOT_FOUND',
  TVA_CODE_TAKEN: 'TVA_CODE_TAKEN',
  TVA_DECLARATION_NOT_FOUND: 'TVA_DECLARATION_NOT_FOUND',
  TVA_DECLARATION_ALREADY_EXISTS: 'TVA_DECLARATION_ALREADY_EXISTS',
  TVA_DECLARATION_INVALID_PERIOD: 'TVA_DECLARATION_INVALID_PERIOD',
  TVA_DECLARATION_NOT_CALCULATED: 'TVA_DECLARATION_NOT_CALCULATED',
  TVA_ALREADY_CENTRALIZED: 'TVA_ALREADY_CENTRALIZED',
  TVA_DECLARATION_CENTRALIZED_CANNOT_CANCEL: 'TVA_DECLARATION_CENTRALIZED_CANNOT_CANCEL',

  // Module 12 — Assets & Depreciation
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  ASSET_CODE_TAKEN: 'ASSET_CODE_TAKEN',
  DEPRECIATION_SCHEDULE_NOT_FOUND: 'DEPRECIATION_SCHEDULE_NOT_FOUND',
  DEPRECIATION_SCHEDULE_ALREADY_POSTED: 'DEPRECIATION_SCHEDULE_ALREADY_POSTED',
  // W3.3 — Cession d'immobilisation (recurring 654/754 vs HAO 812/822).
  ASSET_ALREADY_DISPOSED: 'ASSET_ALREADY_DISPOSED',
  ASSET_DISPOSAL_INVALID_DATE: 'ASSET_DISPOSAL_INVALID_DATE',
  // W4.3 — Moteur amortissement avancé (SOFTY + UOP + dérogatoires).
  ASSET_UOP_UNITS_REQUIRED: 'ASSET_UOP_UNITS_REQUIRED',
  ASSET_UOP_UNITS_OVERFLOW: 'ASSET_UOP_UNITS_OVERFLOW',
  ASSET_DEROGATORY_CONFIG_INVALID: 'ASSET_DEROGATORY_CONFIG_INVALID',

  // Module 14 — Journal entry workflow & electronic signatures.
  ENTRY_SIGNATURE_INVALID_STATUS: 'ENTRY_SIGNATURE_INVALID_STATUS',
  ENTRY_SIGNATURE_ALREADY_SIGNED: 'ENTRY_SIGNATURE_ALREADY_SIGNED',
  ENTRY_SIGNATURE_WRONG_ROLE: 'ENTRY_SIGNATURE_WRONG_ROLE',
  ENTRY_SIGNATURE_REJECT_REASON_REQUIRED: 'ENTRY_SIGNATURE_REJECT_REASON_REQUIRED',

  // Module 15 — Bank reconciliation.
  BANK_ACCOUNT_NOT_FOUND: 'BANK_ACCOUNT_NOT_FOUND',
  BANK_ACCOUNT_CODE_TAKEN: 'BANK_ACCOUNT_CODE_TAKEN',
  BANK_STATEMENT_NOT_FOUND: 'BANK_STATEMENT_NOT_FOUND',
  BANK_STATEMENT_DUPLICATE: 'BANK_STATEMENT_DUPLICATE',
  BANK_STATEMENT_PARSE_FAILED: 'BANK_STATEMENT_PARSE_FAILED',
  BANK_STATEMENT_EMPTY: 'BANK_STATEMENT_EMPTY',
  BANK_STATEMENT_LINE_NOT_FOUND: 'BANK_STATEMENT_LINE_NOT_FOUND',
  BANK_STATEMENT_LINE_ALREADY_MATCHED: 'BANK_STATEMENT_LINE_ALREADY_MATCHED',
  BANK_RECONCILIATION_MATCH_NOT_FOUND: 'BANK_RECONCILIATION_MATCH_NOT_FOUND',
  BANK_RECONCILIATION_AMOUNT_MISMATCH: 'BANK_RECONCILIATION_AMOUNT_MISMATCH',
  BANK_RECONCILIATION_ENTRY_LINE_NOT_VALIDATED: 'BANK_RECONCILIATION_ENTRY_LINE_NOT_VALIDATED',
  BANK_RECONCILIATION_ENTRY_LINE_WRONG_ACCOUNT: 'BANK_RECONCILIATION_ENTRY_LINE_WRONG_ACCOUNT',
  // Module 15 wave 2 — N:M + multi-devises.
  BANK_RECONCILIATION_EMPTY_ENTRY_LINES: 'BANK_RECONCILIATION_EMPTY_ENTRY_LINES',
  BANK_RECONCILIATION_DUPLICATE_ENTRY_LINES: 'BANK_RECONCILIATION_DUPLICATE_ENTRY_LINES',
  BANK_FX_RATE_NOT_FOUND: 'BANK_FX_RATE_NOT_FOUND',

  // Module 16 wave 3.4 — Réévaluation FX clôture d'exercice (article 54 AU).
  FX_REEVAL_NO_FX_BALANCES: 'FX_REEVAL_NO_FX_BALANCES',
  FX_REEVAL_RATE_MISSING: 'FX_REEVAL_RATE_MISSING',
  FX_REEVAL_ALREADY_EXECUTED: 'FX_REEVAL_ALREADY_EXECUTED',
  FX_REEVAL_NOT_REVERSIBLE: 'FX_REEVAL_NOT_REVERSIBLE',

  // Module 21 — Collaboration (demandes de justificatifs, commentaires).
  COLLAB_REQUEST_NOT_FOUND: 'COLLAB_REQUEST_NOT_FOUND',
  COLLAB_TITLE_REQUIRED: 'COLLAB_TITLE_REQUIRED',
  COLLAB_LINKED_NOT_FOUND: 'COLLAB_LINKED_NOT_FOUND',
  COLLAB_INVALID_TRANSITION: 'COLLAB_INVALID_TRANSITION',
  COLLAB_COMMENT_EMPTY: 'COLLAB_COMMENT_EMPTY',
  COLLAB_REQUEST_CLOSED: 'COLLAB_REQUEST_CLOSED',

  // W3.1 — Provisions pour risques et charges SYSCOHADA.
  PROVISION_NOT_FOUND: 'PROVISION_NOT_FOUND',
  PROVISION_INVALID_AMOUNT: 'PROVISION_INVALID_AMOUNT',
  PROVISION_INSUFFICIENT_BALANCE: 'PROVISION_INSUFFICIENT_BALANCE',
  PROVISION_NOT_ACTIVE: 'PROVISION_NOT_ACTIVE',

  // W3.2 — Tests de valeur immo + stocks (App. 44 SYSCOHADA).
  IMPAIRMENT_ASSET_NOT_FOUND: 'IMPAIRMENT_ASSET_NOT_FOUND',
  IMPAIRMENT_INVENTORY_NOT_FOUND: 'IMPAIRMENT_INVENTORY_NOT_FOUND',
  IMPAIRMENT_INVALID_AMOUNT: 'IMPAIRMENT_INVALID_AMOUNT',
  IMPAIRMENT_REPRISE_EXCEEDS_HISTORY: 'IMPAIRMENT_REPRISE_EXCEEDS_HISTORY',

  // W3.5 — Régularisations périodiques (CCA/PCA/CAP/PAR) SYSCOHADA.
  REGULARIZATION_BATCH_NOT_FOUND: 'REGULARIZATION_BATCH_NOT_FOUND',
  REGULARIZATION_BATCH_NOT_DRAFT: 'REGULARIZATION_BATCH_NOT_DRAFT',
  REGULARIZATION_BATCH_NOT_EXECUTED: 'REGULARIZATION_BATCH_NOT_EXECUTED',
  REGULARIZATION_BATCH_ALREADY_REVERSED: 'REGULARIZATION_BATCH_ALREADY_REVERSED',
  REGULARIZATION_ENTRY_INVALID_TYPE: 'REGULARIZATION_ENTRY_INVALID_TYPE',

  // W4.6 — Effets de commerce SYSCOHADA (Tome 1 G07, R22-R25, App. 12).
  BILL_NOT_FOUND: 'BILL_NOT_FOUND',
  BILL_INVALID_STATE_FOR_ACTION: 'BILL_INVALID_STATE_FOR_ACTION',
  BILL_INVALID_AMOUNT: 'BILL_INVALID_AMOUNT',
  BILL_NEGATIVE_NET: 'BILL_NEGATIVE_NET',

  // W4.4 — Subventions d'investissement SYSCOHADA (Tome 2 chap. 17, App. 66).
  SUBSIDY_NOT_FOUND: 'SUBSIDY_NOT_FOUND',
  SUBSIDY_NOT_ACTIVE: 'SUBSIDY_NOT_ACTIVE',
  SUBSIDY_INVALID_AMOUNT: 'SUBSIDY_INVALID_AMOUNT',
  SUBSIDY_OVERRELEASE: 'SUBSIDY_OVERRELEASE',

  // W4.5 — Crédit-bail / location-acquisition SYSCOHADA (Tome 2 chap. 8, App. 37-38).
  LEASE_NOT_FOUND: 'LEASE_NOT_FOUND',
  LEASE_NOT_ACTIVE: 'LEASE_NOT_ACTIVE',
  LEASE_INSTALLMENT_NOT_FOUND: 'LEASE_INSTALLMENT_NOT_FOUND',
  LEASE_INSTALLMENT_ALREADY_PAID: 'LEASE_INSTALLMENT_ALREADY_PAID',
  LEASE_IMPLICIT_RATE_CALCULATION_FAILED: 'LEASE_IMPLICIT_RATE_CALCULATION_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * Exhaustive list of declared codes — useful for tests that must iterate
 * over the whole catalogue (e.g. ensure each code has a mapped HTTP status,
 * or generate per-code e2e error envelope tests, cf. BE-TEST-09).
 */
export const ALL_ERROR_CODES: ReadonlyArray<ErrorCode> = Object.values(
  ERROR_CODES,
) as ReadonlyArray<ErrorCode>;

/**
 * Type guard for runtime values coming from outside the type system
 * (HTTP payloads, persisted data, etc.).
 */
export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === 'string' && (ALL_ERROR_CODES as ReadonlyArray<string>).includes(value);
}
