/**
 * Mapping from stable business error codes to HTTP status codes.
 *
 * This mapping is the **single source of truth** for the HTTP status
 * returned to clients. It is consumed by:
 *  - `AppException` (default `status` for a given `code`),
 *  - the global exception filter (BE-BOOT-06) to format the response,
 *  - the OpenAPI/error documentation (BE-DOC-01).
 *
 * The `Record<ErrorCode, number>` constraint guarantees at compile time
 * that every code declared in `error-codes.ts` has an explicit HTTP status
 * — a new code without a mapping fails to build.
 */

import { ERROR_CODES, type ErrorCode } from './error-codes';

export const ERROR_CODE_TO_HTTP_STATUS: Readonly<Record<ErrorCode, number>> = {
  // 401 — credentials missing / invalid / MFA required (auth not satisfied).
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 401,
  [ERROR_CODES.AUTH_INVALID_TOKEN]: 401,
  [ERROR_CODES.AUTH_MFA_REQUIRED]: 401,
  [ERROR_CODES.AUTH_MFA_INVALID_CODE]: 401,
  [ERROR_CODES.AUTH_MFA_NOT_ENROLLED]: 401,
  [ERROR_CODES.AUTH_REFRESH_REUSE]: 401,

  // 403 — caller is authenticated but not authorized.
  [ERROR_CODES.FORBIDDEN_ROLE]: 403,
  [ERROR_CODES.FORBIDDEN_PERMISSION]: 403,
  [ERROR_CODES.FORBIDDEN_NO_MEMBERSHIP]: 403,
  [ERROR_CODES.RBAC_NO_POLICY_DECLARED]: 403,
  [ERROR_CODES.RBAC_SYSTEM_ROLE_LOCKED]: 403,

  // 404 — fail-closed, also used by TenantGuard to avoid disclosure.
  [ERROR_CODES.ORG_NOT_FOUND]: 404,
  [ERROR_CODES.INVITATION_NOT_FOUND]: 404,
  [ERROR_CODES.CHART_ACCOUNT_NOT_FOUND]: 404,
  [ERROR_CODES.IMPORT_SESSION_NOT_FOUND]: 404,
  [ERROR_CODES.IMPORT_FILE_NOT_FOUND]: 404,
  [ERROR_CODES.DOC_NOT_FOUND]: 404,

  // 409 — state conflict (duplicate, invariant violation, already used).
  [ERROR_CODES.AUTH_EMAIL_TAKEN]: 409,
  [ERROR_CODES.AUTH_MFA_ALREADY_ENABLED]: 409,
  [ERROR_CODES.ORG_LAST_ADMIN]: 409,
  [ERROR_CODES.INVITATION_ALREADY_USED]: 409,
  [ERROR_CODES.INVITATION_ALREADY_PENDING]: 409,
  [ERROR_CODES.INVITATION_REVOKED]: 409,
  [ERROR_CODES.CHART_ACCOUNT_CODE_TAKEN]: 409,
  [ERROR_CODES.CHART_ACCOUNT_NOT_DELETABLE]: 409,
  [ERROR_CODES.IMPORT_SESSION_NOT_DRAFT]: 409,
  [ERROR_CODES.IMPORT_SESSION_NOT_PARSED]: 409,
  [ERROR_CODES.IMPORT_SESSION_NOT_VALID]: 409,
  [ERROR_CODES.LETTERING_LINE_ALREADY_USED]: 409,
  [ERROR_CODES.LETTERING_ALREADY_BROKEN]: 409,
  [ERROR_CODES.IMPORT_FILE_DUPLICATE]: 409,

  // 410 — the targeted resource existed but is no longer usable.
  [ERROR_CODES.INVITATION_EXPIRED]: 410,

  // 404 — Module 4 Transformation Engine.
  [ERROR_CODES.TRANSFORMATION_SOURCE_ENTRY_NOT_FOUND]: 404,
  [ERROR_CODES.LETTERING_NOT_FOUND]: 404,

  // 422 — Module 4 Transformation Engine.
  [ERROR_CODES.TRANSFORMATION_NO_FIELD_CHANGED]: 422,
  [ERROR_CODES.TRANSFORMATION_ADJUSTMENT_INVALID]: 422,

  // 422 — input rejected by validation (semantic, not syntactic).
  [ERROR_CODES.AUTH_WEAK_PASSWORD]: 422,
  [ERROR_CODES.ORG_NOTHING_TO_UPDATE]: 422,
  [ERROR_CODES.CHART_ACCOUNT_INVALID_PARENT]: 422,
  [ERROR_CODES.CHART_ACCOUNT_INVALID_CODE]: 422,
  [ERROR_CODES.CHART_ACCOUNT_IMMUTABLE_CODE]: 422,
  [ERROR_CODES.ACCOUNTING_SYSTEM_REQUIRED]: 422,
  [ERROR_CODES.IMPORT_UNSUPPORTED_FORMAT]: 422,
  [ERROR_CODES.IMPORT_FILE_PARSE_FAILED]: 422,
  [ERROR_CODES.IMPORT_COMMIT_UNBALANCED_GROUP]: 422,
  [ERROR_CODES.LETTERING_UNBALANCED]: 422,
  [ERROR_CODES.LETTERING_MIXED_ACCOUNTS]: 422,
  [ERROR_CODES.LETTERING_NOT_PARTNER_ACCOUNT]: 422,
  [ERROR_CODES.LETTERING_LINES_REQUIRED]: 422,
  [ERROR_CODES.LETTERING_LINE_NOT_VALIDATED]: 422,
  [ERROR_CODES.REPORT_INVALID_DATE_RANGE]: 422,
  [ERROR_CODES.DOC_FILE_REQUIRED]: 422,
  [ERROR_CODES.DOC_MIME_REJECTED]: 422,

  // 413 — payload too large (file upload exceeded configured limit).
  [ERROR_CODES.IMPORT_FILE_TOO_LARGE]: 413,
  [ERROR_CODES.DOC_FILE_TOO_LARGE]: 413,

  // 500 — infra failure surfaced to the caller (storage driver crashed).
  [ERROR_CODES.DOC_STORAGE_FAILURE]: 500,
  [ERROR_CODES.IMPORT_COMMIT_FAILED]: 500,

  // Module 5 — Rule Engine.
  [ERROR_CODES.RULE_NOT_FOUND]: 404,
  [ERROR_CODES.RULE_INVALID_CONDITION]: 422,
  [ERROR_CODES.RULE_INVALID_ACTION]: 422,

  // Module 6 — Workflow engine.
  [ERROR_CODES.WORKFLOW_INSTANCE_NOT_FOUND]: 404,
  [ERROR_CODES.WORKFLOW_TRANSITION_INVALID]: 409,
  [ERROR_CODES.WORKFLOW_LOCKED]: 409,

  // Module 8 — Journals & Entries.
  [ERROR_CODES.JOURNAL_NOT_FOUND]: 404,
  [ERROR_CODES.JOURNAL_ENTRY_NOT_FOUND]: 404,
  [ERROR_CODES.ACCOUNTING_PERIOD_NOT_FOUND]: 404,
  [ERROR_CODES.JOURNAL_CODE_TAKEN]: 409,
  [ERROR_CODES.JOURNAL_ENTRY_IMMUTABLE]: 409,
  [ERROR_CODES.JOURNAL_ENTRY_ALREADY_CANCELLED]: 409,
  [ERROR_CODES.ACCOUNTING_PERIOD_CLOSED]: 409,
  [ERROR_CODES.ACCOUNTING_PERIOD_HAS_DRAFTS]: 409,
  [ERROR_CODES.ACCOUNTING_PERIOD_OVERLAPS]: 409,
  [ERROR_CODES.JOURNAL_ENTRY_UNBALANCED]: 422,
  [ERROR_CODES.JOURNAL_ENTRY_EMPTY_LINES]: 422,
  [ERROR_CODES.JOURNAL_ENTRY_NON_POSTING_ACCOUNT]: 422,
  [ERROR_CODES.JOURNAL_ENTRY_INVALID_LINE]: 422,
  [ERROR_CODES.ACCOUNTING_PERIOD_REOPEN_REASON_REQUIRED]: 422,

  // Module 13 — TVA & Déclarations fiscales.
  [ERROR_CODES.TVA_CODE_NOT_FOUND]: 404,
  [ERROR_CODES.TVA_CODE_TAKEN]: 409,
  [ERROR_CODES.TVA_DECLARATION_NOT_FOUND]: 404,
  [ERROR_CODES.TVA_DECLARATION_ALREADY_EXISTS]: 409,
  [ERROR_CODES.TVA_DECLARATION_INVALID_PERIOD]: 422,
  [ERROR_CODES.TVA_DECLARATION_NOT_CALCULATED]: 409,

  // Module 12 — Assets & Depreciation.
  [ERROR_CODES.ASSET_NOT_FOUND]: 404,
  [ERROR_CODES.ASSET_CODE_TAKEN]: 409,
  [ERROR_CODES.DEPRECIATION_SCHEDULE_NOT_FOUND]: 404,
  [ERROR_CODES.DEPRECIATION_SCHEDULE_ALREADY_POSTED]: 409,

  // Module 14 — Journal entry workflow & electronic signatures.
  [ERROR_CODES.ENTRY_SIGNATURE_INVALID_STATUS]: 409,
  [ERROR_CODES.ENTRY_SIGNATURE_ALREADY_SIGNED]: 409,
  [ERROR_CODES.ENTRY_SIGNATURE_WRONG_ROLE]: 403,
  [ERROR_CODES.ENTRY_SIGNATURE_REJECT_REASON_REQUIRED]: 422,
};

/**
 * Resolve the HTTP status associated with a business error code.
 *
 * Used by `AppException` and the global exception filter (BE-BOOT-06).
 */
export function getHttpStatusForCode(code: ErrorCode): number {
  return ERROR_CODE_TO_HTTP_STATUS[code];
}
