/**
 * Plan comptable de référence OHADA — SYSCOHADA AUDCIF révisé.
 *
 * Source : Acte Uniforme OHADA portant organisation et harmonisation
 * des comptabilités des entreprises (révisé 2017, applicable depuis le
 * 1ᵉʳ janvier 2018), annexe « Plan comptable général SYSCOHADA ».
 *
 * STATUT : SQUELETTE — seules les racines de classe (1 chiffre) et
 * quelques comptes principaux universellement connus sont seedés ici à
 * titre de validation de la structure. Le seed exhaustif (~800 comptes
 * pour le Normal) est livré par BE-PC-01 / BE-PC-02 et DOIT être
 * validé contre le PDF officiel AUDCIF par un expert-comptable avant
 * mise en production. Voir l'issue projet-ferme-1f8 dans bd.
 *
 * Convention :
 * - `code`            : chiffres uniquement, longueur 2..10.
 * - `class`           : premier chiffre du code.
 * - `account_type`    : `TITLE` (nœud) ou `POSTING` (feuille). Dans le
 *                       plan AUDCIF officiel, tous les comptes à 2-3
 *                       chiffres sont quasi systématiquement TITLE.
 * - `normal_balance`  : D pour classes 2/3/5/6 ; C pour classes 1/7 ;
 *                       variable pour classes 4/8/9 (fixé par compte).
 * - `applicable_systems` : sous-ensemble non vide de {NORMAL, MINIMAL,
 *                       ALLEGE}. Les comptes purement structurels (1-3
 *                       chiffres) sont applicables aux trois systèmes.
 */
import type { ReferenceAccountSeed } from '../types/accounting-system';

export const OHADA_REFERENCE_CHART: ReadonlyArray<ReferenceAccountSeed> = [
  // ─── Classe 1 — Comptes de ressources durables ────────────────────────
  {
    code: '1',
    label: 'Ressources durables',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '10',
    label: 'Capital',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '11',
    label: 'Réserves',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '12',
    label: 'Report à nouveau',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '13',
    label: "Résultat net de l'exercice",
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '14',
    label: "Subventions d'investissement",
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '15',
    label: 'Provisions réglementées et fonds assimilés',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '16',
    label: 'Emprunts et dettes assimilées',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '17',
    label: 'Dettes de crédit-bail et contrats assimilés',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '18',
    label:
      'Dettes liées à des participations et comptes de liaison des établissements et sociétés en participation',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '19',
    label: 'Provisions pour risques et charges',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },

  // ─── Classe 2 — Comptes d'actif immobilisé ────────────────────────────
  {
    code: '2',
    label: 'Actif immobilisé',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '20',
    label: 'Charges immobilisées',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '21',
    label: 'Immobilisations incorporelles',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '22',
    label: 'Terrains',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '23',
    label: 'Bâtiments, installations techniques et agencements',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '24',
    label: 'Matériel, mobilier et actifs biologiques',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '25',
    label: 'Avances et acomptes versés sur immobilisations',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '26',
    label: 'Titres de participation',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '27',
    label: 'Autres immobilisations financières',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '28',
    label: 'Amortissements',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '29',
    label: 'Dépréciations des immobilisations',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },

  // ─── Classe 3 — Comptes de stocks ─────────────────────────────────────
  {
    code: '3',
    label: 'Stocks',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '31',
    label: 'Marchandises',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '32',
    label: 'Matières premières et fournitures liées',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '33',
    label: 'Autres approvisionnements',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '34',
    label: 'Produits en cours',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '35',
    label: 'Services en cours',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '36',
    label: 'Produits finis',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '37',
    label: 'Produits intermédiaires et résiduels',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '38',
    label: 'Stocks en cours de route, en consignation ou en dépôt',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '39',
    label: 'Dépréciations des stocks',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },

  // ─── Classe 4 — Comptes de tiers ──────────────────────────────────────
  // Sens variable selon le sous-compte : 40 et 42-47 plutôt C (dettes
  // ou collecteurs de TVA collectée), 41 et 48-49 plutôt D (créances et
  // dépréciations).
  {
    code: '4',
    label: 'Tiers',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '40',
    label: 'Fournisseurs et comptes rattachés',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '41',
    label: 'Clients et comptes rattachés',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '42',
    label: 'Personnel',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '43',
    label: 'Organismes sociaux',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '44',
    label: 'État et collectivités publiques',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '45',
    label: 'Organismes internationaux',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '46',
    label: 'Associés et groupe',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '47',
    label: 'Débiteurs et créditeurs divers',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '48',
    label: 'Créances et dettes hors activités ordinaires (HAO)',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '49',
    label: 'Dépréciations et provisions pour risques à court terme',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },

  // ─── Classe 5 — Comptes de trésorerie ─────────────────────────────────
  {
    code: '5',
    label: 'Trésorerie',
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '50',
    label: 'Titres de placement',
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '51',
    label: 'Valeurs à encaisser',
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '52',
    label: 'Banques',
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '53',
    label: 'Établissements financiers et assimilés',
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '54',
    label: 'Instruments de monnaie électronique',
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '56',
    label: "Banques, crédits de trésorerie et d'escompte",
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '57',
    label: 'Caisse',
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '58',
    label: "Régies d'avances, accréditifs et virements internes",
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '59',
    label: 'Dépréciations et provisions pour risques à court terme',
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },

  // ─── Classe 6 — Comptes de charges ────────────────────────────────────
  {
    code: '6',
    label: 'Charges des activités ordinaires',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '60',
    label: 'Achats et variations de stocks',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '61',
    label: 'Transports',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '62',
    label: 'Services extérieurs A',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '63',
    label: 'Services extérieurs B',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '64',
    label: 'Impôts et taxes',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '65',
    label: 'Autres charges',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '66',
    label: 'Charges de personnel',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '67',
    label: 'Frais financiers et charges assimilées',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '68',
    label: 'Dotations aux amortissements',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '69',
    label: 'Dotations aux provisions et aux dépréciations',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },

  // ─── Classe 7 — Comptes de produits ───────────────────────────────────
  {
    code: '7',
    label: 'Produits des activités ordinaires',
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '70',
    label: 'Ventes',
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '71',
    label: "Subventions d'exploitation",
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '72',
    label: 'Production immobilisée',
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '73',
    label: 'Variations des stocks de biens et de services produits',
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '75',
    label: 'Autres produits',
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '77',
    label: 'Revenus financiers et produits assimilés',
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '78',
    label: 'Transferts de charges',
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '79',
    label: 'Reprises de provisions et de dépréciations',
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },

  // ─── Classe 8 — Autres charges et autres produits HAO ─────────────────
  {
    code: '8',
    label: 'Autres charges et autres produits',
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '81',
    label: "Valeurs comptables des cessions d'immobilisations",
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '82',
    label: "Produits des cessions d'immobilisations",
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '83',
    label: 'Charges hors activités ordinaires',
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '84',
    label: 'Produits hors activités ordinaires',
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '85',
    label: 'Dotations hors activités ordinaires',
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '86',
    label: 'Reprises hors activités ordinaires',
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '87',
    label: 'Participation des travailleurs',
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '88',
    label: "Subventions d'équilibre",
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '89',
    label: 'Impôts sur le résultat',
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },

  // ─── Classe 9 — Comptes analytiques (facultatifs) ─────────────────────
  {
    code: '9',
    label: 'Comptes des engagements hors bilan et comptabilité analytique',
    class: 9,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
];
