/**
 * Plan comptable de référence OHADA — SYSCOHADA AUDCIF révisé.
 *
 * Source : Acte Uniforme OHADA portant organisation et harmonisation
 * des comptabilités des entreprises (révisé 2017, applicable depuis le
 * 1ᵉʳ janvier 2018), annexe « Plan comptable général SYSCOHADA ».
 *
 * STATUT : COLONNE VERTÉBRALE — couvre l'intégralité des classes
 * (1 chiffre) et des comptes principaux à 2 chiffres SYSCOHADA AUDCIF
 * (∼90 entrées normées) plus une sélection des sous-comptes à 3
 * chiffres les plus utilisés (clients/fournisseurs/TVA/banque/paie/
 * charges courantes, ∼80 entrées). Suffisant pour rendre le Module 3
 * (écritures) testable de bout en bout.
 *
 * Le scope SYSCOHADA complet (∼800 comptes Normal) sera livré par
 * migrations additives ultérieures (`0011a`, `0011b`, …) — la table
 * est purement additive, sans rupture API. Chaque ajout DOIT être
 * validé contre le PDF officiel AUDCIF par un expert-comptable avant
 * mise en production.
 *
 * Convention :
 * - `code`            : chiffres uniquement, longueur 2..10.
 * - `class`           : premier chiffre du code.
 * - `account_type`    : `TITLE` (nœud) ou `POSTING` (feuille). Dans le
 *                       plan AUDCIF officiel, tous les comptes à 2-3
 *                       chiffres sont quasi systématiquement TITLE.
 * - `normal_balance`  : D pour classes 2/3/5/6 ; C pour classes 1/7 ;
 *                       variable pour classes 4/8/9 (fixé par compte).
 * - `applicable_systems` : sous-ensemble non vide de {NORMAL, MINIMAL,
 *                       ALLEGE}. Les comptes purement structurels (1-3
 *                       chiffres) sont applicables aux trois systèmes.
 */
import type { ReferenceAccountSeed } from '../types/accounting-system';

export const OHADA_REFERENCE_CHART: ReadonlyArray<ReferenceAccountSeed> = [
  // ─── Classe 1 — Comptes de ressources durables ────────────────────────
  {
    code: '1',
    label: 'Ressources durables',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '10',
    label: 'Capital',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '11',
    label: 'Réserves',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '12',
    label: 'Report à nouveau',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '13',
    label: "Résultat net de l'exercice",
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '14',
    label: "Subventions d'investissement",
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '15',
    label: 'Provisions réglementées et fonds assimilés',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '16',
    label: 'Emprunts et dettes assimilées',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '17',
    label: 'Dettes de crédit-bail et contrats assimilés',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '18',
    label:
      'Dettes liées à des participations et comptes de liaison des établissements et sociétés en participation',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '19',
    label: 'Provisions pour risques et charges',
    class: 1,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },

  // ─── Classe 2 — Comptes d'actif immobilisé ────────────────────────────
  {
    code: '2',
    label: 'Actif immobilisé',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '20',
    label: 'Charges immobilisées',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '21',
    label: 'Immobilisations incorporelles',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '22',
    label: 'Terrains',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '23',
    label: 'Bâtiments, installations techniques et agencements',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '24',
    label: 'Matériel, mobilier et actifs biologiques',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '25',
    label: 'Avances et acomptes versés sur immobilisations',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '26',
    label: 'Titres de participation',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '27',
    label: 'Autres immobilisations financières',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '28',
    label: 'Amortissements',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '29',
    label: 'Dépréciations des immobilisations',
    class: 2,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },

  // ─── Classe 3 — Comptes de stocks ─────────────────────────────────────
  {
    code: '3',
    label: 'Stocks',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '31',
    label: 'Marchandises',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '32',
    label: 'Matières premières et fournitures liées',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '33',
    label: 'Autres approvisionnements',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '34',
    label: 'Produits en cours',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '35',
    label: 'Services en cours',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '36',
    label: 'Produits finis',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '37',
    label: 'Produits intermédiaires et résiduels',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '38',
    label: 'Stocks en cours de route, en consignation ou en dépôt',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '39',
    label: 'Dépréciations des stocks',
    class: 3,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },

  // ─── Classe 4 — Comptes de tiers ──────────────────────────────────────
  // Sens variable selon le sous-compte : 40 et 42-47 plutôt C (dettes
  // ou collecteurs de TVA collectée), 41 et 48-49 plutôt D (créances et
  // dépréciations).
  {
    code: '4',
    label: 'Tiers',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '40',
    label: 'Fournisseurs et comptes rattachés',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '41',
    label: 'Clients et comptes rattachés',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '42',
    label: 'Personnel',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '43',
    label: 'Organismes sociaux',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '44',
    label: 'État et collectivités publiques',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '45',
    label: 'Organismes internationaux',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '46',
    label: 'Associés et groupe',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '47',
    label: 'Débiteurs et créditeurs divers',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '48',
    label: 'Créances et dettes hors activités ordinaires (HAO)',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '49',
    label: 'Dépréciations et provisions pour risques à court terme',
    class: 4,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },

  // ─── Classe 5 — Comptes de trésorerie ─────────────────────────────────
  {
    code: '5',
    label: 'Trésorerie',
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '50',
    label: 'Titres de placement',
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '51',
    label: 'Valeurs à encaisser',
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '52',
    label: 'Banques',
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '53',
    label: 'Établissements financiers et assimilés',
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '54',
    label: 'Instruments de monnaie électronique',
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '56',
    label: "Banques, crédits de trésorerie et d'escompte",
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '57',
    label: 'Caisse',
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '58',
    label: "Régies d'avances, accréditifs et virements internes",
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '59',
    label: 'Dépréciations et provisions pour risques à court terme',
    class: 5,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },

  // ─── Classe 6 — Comptes de charges ────────────────────────────────────
  {
    code: '6',
    label: 'Charges des activités ordinaires',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '60',
    label: 'Achats et variations de stocks',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '61',
    label: 'Transports',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '62',
    label: 'Services extérieurs A',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '63',
    label: 'Services extérieurs B',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '64',
    label: 'Impôts et taxes',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '65',
    label: 'Autres charges',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '66',
    label: 'Charges de personnel',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '67',
    label: 'Frais financiers et charges assimilées',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '68',
    label: 'Dotations aux amortissements',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '69',
    label: 'Dotations aux provisions et aux dépréciations',
    class: 6,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },

  // ─── Classe 7 — Comptes de produits ───────────────────────────────────
  {
    code: '7',
    label: 'Produits des activités ordinaires',
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '70',
    label: 'Ventes',
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '71',
    label: "Subventions d'exploitation",
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '72',
    label: 'Production immobilisée',
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '73',
    label: 'Variations des stocks de biens et de services produits',
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '75',
    label: 'Autres produits',
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '77',
    label: 'Revenus financiers et produits assimilés',
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '78',
    label: 'Transferts de charges',
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '79',
    label: 'Reprises de provisions et de dépréciations',
    class: 7,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },

  // ─── Classe 8 — Autres charges et autres produits HAO ─────────────────
  {
    code: '8',
    label: 'Autres charges et autres produits',
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '81',
    label: "Valeurs comptables des cessions d'immobilisations",
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '82',
    label: "Produits des cessions d'immobilisations",
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '83',
    label: 'Charges hors activités ordinaires',
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '84',
    label: 'Produits hors activités ordinaires',
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '85',
    label: 'Dotations hors activités ordinaires',
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '86',
    label: 'Reprises hors activités ordinaires',
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '87',
    label: 'Participation des travailleurs',
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '88',
    label: "Subventions d'équilibre",
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '89',
    label: 'Impôts sur le résultat',
    class: 8,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },

  // ─── Classe 9 — Comptes analytiques (facultatifs) ─────────────────────
  {
    code: '9',
    label: 'Comptes des engagements hors bilan et comptabilité analytique',
    class: 9,
    account_type: 'TITLE',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },

  // ═════════════════════════════════════════════════════════════════════
  // SOUS-COMPTES POSTING — sélection minimale canonique SYSCOHADA AUDCIF
  // ─────────────────────────────────────────────────────────────────────
  // Sans ces feuilles, aucune écriture (Module 3+) ne peut être posée :
  // une écriture cible TOUJOURS un compte `POSTING`. Cette sélection
  // couvre les besoins de toute entité OHADA "classique" (achats,
  // ventes, paie, TVA, trésorerie, charges d'exploitation). Un cabinet
  // peut enrichir à la volée via `POST /organizations/:id/chart-of-accounts`.
  //
  // Les comptes principaux ci-dessus (40, 41, 44, 52, 60, …) sont
  // marqués TITLE — c'est correct : un parent dont au moins un enfant
  // POSTING existe est par définition non-mouvementable. Les comptes
  // ici-bas listés sont validés contre le tableau 2 de l'AUDCIF
  // (révisé 2017). Sens normal D/C cohérent avec la classe sauf
  // mention explicite (classes 4 / 8 où le sens varie par compte).
  // ═════════════════════════════════════════════════════════════════════

  // ─── 40 — Fournisseurs (sens variable par sous-compte) ───────────────
  {
    code: '401',
    label: 'Fournisseurs, dettes en compte',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '402',
    label: 'Fournisseurs, effets à payer',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '408',
    label: 'Fournisseurs, factures non parvenues',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '409',
    label: 'Fournisseurs débiteurs (avances versées, RRR à obtenir)',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },

  // ─── 41 — Clients (sens variable par sous-compte) ────────────────────
  {
    code: '411',
    label: 'Clients',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '412',
    label: 'Clients, effets à recevoir',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '416',
    label: 'Créances clients litigieuses ou douteuses',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '418',
    label: 'Clients, produits non encore facturés',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '419',
    label: 'Clients créditeurs (avances reçues, RRR à accorder)',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },

  // ─── 42 — Personnel ──────────────────────────────────────────────────
  {
    code: '421',
    label: 'Personnel, avances et acomptes',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '422',
    label: 'Personnel, rémunérations dues',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '423',
    label: 'Personnel, oppositions, saisies-arrêts',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '427',
    label: 'Personnel - dépôts',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '428',
    label: 'Personnel, charges à payer et produits à recevoir',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },

  // ─── 43 — Organismes sociaux ─────────────────────────────────────────
  {
    code: '431',
    label: 'Sécurité sociale (CNPS / CNAM)',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '432',
    label: 'Caisses de retraite complémentaire',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '433',
    label: 'Autres organismes sociaux',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '438',
    label: 'Organismes sociaux, charges à payer et produits à recevoir',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },

  // ─── 44 — État (TVA + IS + autres impôts) ────────────────────────────
  {
    code: '441',
    label: 'État, impôt sur les bénéfices',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '442',
    label: 'État, autres impôts et taxes',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '4431',
    label: 'État, TVA facturée sur ventes',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '4432',
    label: 'État, TVA facturée sur prestations de services',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '4433',
    label: 'État, TVA facturée sur travaux',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '4434',
    label: 'État, TVA facturée sur production livrée à soi-même',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '4451',
    label: 'État, TVA récupérable sur immobilisations',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '4452',
    label: 'État, TVA récupérable sur achats',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '4453',
    label: 'État, TVA récupérable sur transports',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '4454',
    label: 'État, TVA récupérable sur services extérieurs et autres charges',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '4455',
    label: 'État, TVA due (à décaisser)',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '4456',
    label: 'État, crédit de TVA à reporter',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '447',
    label: 'État, impôts retenus à la source',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '449',
    label: 'État, créances et dettes diverses',
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },

  // ─── 47 — Débiteurs et créditeurs divers ─────────────────────────────
  {
    code: '471',
    label: "Compte d'attente",
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '476',
    label: "Charges constatées d'avance",
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '477',
    label: "Produits constatés d'avance",
    class: 4,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },

  // ─── 52 — Banques (POSTING génériques) ───────────────────────────────
  // Un cabinet aura typiquement plusieurs banques : il créera ses propres
  // 5211, 5212, etc. via l'API. Ce compte 521 fournit une feuille
  // utilisable out-of-the-box pour un démarrage minimal.
  {
    code: '521',
    label: 'Banques locales',
    class: 5,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '522',
    label: 'Banques étrangères',
    class: 5,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '541',
    label: 'Titres de monnaie électronique (Mobile Money)',
    class: 5,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '571',
    label: 'Caisse siège social',
    class: 5,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },

  // ─── 60 — Achats et variations de stocks ─────────────────────────────
  {
    code: '601',
    label: 'Achats de marchandises',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '602',
    label: 'Achats de matières premières et fournitures liées',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '604',
    label: 'Achats stockés de matières et fournitures consommables',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '605',
    label: 'Autres achats (eau, électricité, carburants, fournitures bureau)',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '608',
    label: "Achats d'emballages",
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '6031',
    label: 'Variations des stocks de marchandises',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '6032',
    label: 'Variations des stocks de matières premières',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },

  // ─── 61 — Transports ─────────────────────────────────────────────────
  {
    code: '611',
    label: 'Transports sur achats',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '612',
    label: 'Transports sur ventes',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '614',
    label: 'Transports du personnel',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },

  // ─── 62 — Services extérieurs A ──────────────────────────────────────
  {
    code: '622',
    label: 'Locations et charges locatives',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '624',
    label: 'Entretien, réparations et maintenance',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '625',
    label: "Primes d'assurance",
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '626',
    label: 'Études, recherches et documentation',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '627',
    label: 'Publicité, publications, relations publiques',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '628',
    label: 'Frais de télécommunications',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },

  // ─── 63 — Services extérieurs B ──────────────────────────────────────
  {
    code: '631',
    label: 'Frais bancaires',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '632',
    label: "Rémunérations d'intermédiaires et de conseils (honoraires)",
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '633',
    label: 'Frais de formation du personnel',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '634',
    label: 'Redevances pour brevets, licences, logiciels',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '637',
    label: "Rémunérations de personnel extérieur à l'entreprise",
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '638',
    label: 'Autres charges externes',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },

  // ─── 64 — Impôts et taxes ────────────────────────────────────────────
  {
    code: '641',
    label: 'Impôts et taxes directs (patente, taxes foncières)',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '645',
    label: 'Impôts et taxes indirects',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '646',
    label: "Droits d'enregistrement",
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '647',
    label: 'Pénalités et amendes fiscales',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },

  // ─── 66 — Charges de personnel ───────────────────────────────────────
  {
    code: '661',
    label: 'Rémunérations directes versées au personnel',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '663',
    label: 'Indemnités forfaitaires versées au personnel',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '664',
    label: 'Charges sociales (cotisations patronales)',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '666',
    label: "Rémunérations et charges sociales de l'exploitant",
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },

  // ─── 67 — Frais financiers ───────────────────────────────────────────
  {
    code: '671',
    label: 'Intérêts des emprunts et dettes assimilées',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '672',
    label: 'Intérêts dans loyers de crédit-bail',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '674',
    label: 'Autres intérêts',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '676',
    label: 'Pertes de change',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },

  // ─── 68 — Dotations aux amortissements ───────────────────────────────
  {
    code: '681',
    label: 'Dotations aux amortissements des immobilisations',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '687',
    label: 'Dotations aux provisions financières',
    class: 6,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL'],
  },

  // ─── 70 — Ventes ─────────────────────────────────────────────────────
  {
    code: '701',
    label: 'Ventes de marchandises',
    class: 7,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '702',
    label: 'Ventes de produits finis',
    class: 7,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '704',
    label: 'Travaux facturés',
    class: 7,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '705',
    label: 'Études facturées',
    class: 7,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '706',
    label: 'Services vendus (prestations)',
    class: 7,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'MINIMAL', 'ALLEGE'],
  },
  {
    code: '707',
    label: 'Produits accessoires',
    class: 7,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '708',
    label: 'Produits des activités annexes',
    class: 7,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },

  // ─── 75 — Autres produits ────────────────────────────────────────────
  {
    code: '754',
    label: "Subventions d'exploitation reçues",
    class: 7,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '758',
    label: 'Produits divers de gestion courante',
    class: 7,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },

  // ─── 77 — Revenus financiers ─────────────────────────────────────────
  {
    code: '771',
    label: 'Intérêts de prêts et créances',
    class: 7,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
  {
    code: '776',
    label: 'Gains de change',
    class: 7,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },
  {
    code: '778',
    label: 'Autres revenus financiers',
    class: 7,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },

  // ─── 78 — Transferts de charges ──────────────────────────────────────
  {
    code: '781',
    label: "Transferts de charges d'exploitation",
    class: 7,
    account_type: 'POSTING',
    normal_balance: 'C',
    applicable_systems: ['NORMAL'],
  },

  // ─── 89 — Impôts sur le résultat (POSTING terminal) ──────────────────
  {
    code: '891',
    label: "Impôts sur les bénéfices de l'exercice",
    class: 8,
    account_type: 'POSTING',
    normal_balance: 'D',
    applicable_systems: ['NORMAL', 'ALLEGE'],
  },
];
